name: First Workflow   # Name of the workflow

# Trigger settings
on:
  push:    # Run the workflow when a push occurs
    branches:
      - main     # Trigger only when pushing to the 'main' branch

jobs:     # List of jobs in this workflow
  example-job:     # Name of the first job
    runs-on: ubuntu-latest    # Use the latest Ubuntu runner

    steps:     # Sequence of steps for this job
      - name: Print a welcome message
        run: echo "Welcome to our first GitHub Actions Workflow!"
