# This workflow runs when a push or pull request is made to main or release/** affecting src/**
name: Push and PR Workflow

on:
  push: 
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"
  pull_request:
    branches:
      - main
      - "release/**"

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y nodejs npm

      - name: Run tests
        run: npm test
